CREATE SEQUENCE profileImg_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE TABLE profileImg (
 codigo BIGINT GENERATED BY DEFAULT AS SEQUENCE profileImg_id_seq PRIMARY KEY ,
 profileimg BYTE(1024) NOT NULL ,
 codigo_pessoa BIGINT NOT NULL,
 FOREIGN KEY (codigo_pessoa) REFERENCES pessoa(codigo)
);